### ISSUE TITLE
Failed to upload file to Object Storage.

### ISSUE THREAD

**Issue by nancyPandya** [watson-developer-cloud/visual-recognition-coreml#11]
When I try to upload .zip file , Ther r not allowing me to upload, showing this error

**Comment by mediumTaj** [comment]
@nancyPandya Can you please show the error?

**Comment by mediumTaj** [comment]
Closing this for now. If you are still having issues please reopen with more details.

**Comment by JoshBoluga** [comment]
I'm not sure if this is the right place, but searching for this error message, this is the only mention of it I found. This is happening on "dataplatform.ibm.com". If I'm in the wrong place, please let me know.

I'm getting this error all the time while trying to upload a data set. On the button on "Drop files here or browse for files to upload." I click on 'browse' choose a zip file of images and it starts uploading. I'm not sure if it finishes first or just stops part-way. It presents the error "Failed to upload file to Object Storage." And the only option is to dismiss.
