### ISSUE TITLE
Update SDK to support XCode 10

### ISSUE THREAD

**Issue by Zickox** [watson-developer-cloud/visual-recognition-coreml#22]
The Core Ml Custom example work fine with Xcode 9.3 but with Xcode 10 does not recognize the module VisualRecognitionV3, any idea how to solve it?

**Comment by germanattanasio** [comment]
@mediumTaj who can help with this?

**Comment by mediumTaj** [comment]
I’ll be in tonight. Let me take a look at this tonight or tomorrow.

**Comment by mediumTaj** [comment]
@Zickox Is XCode 10 a beta version?

**Comment by Zickox** [comment]
@mediumTaj Yep it is, xcode 10 beta was released in the last Apple wwdc also xcode 10 beta includes swift 4.2, probably the module VisualRecognitionV3 was compiled for an older version of swift and maybe that's why it is not recognized in xcode 10.

**Comment by mediumTaj** [comment]
It looks like there will need to be some changes in the Swift SDK for Xcode 10. Thanks for pointing this out

**Comment by mediumTaj** [comment]
Tracking SDK update in this issue
https://github.com/watson-developer-cloud/swift-sdk/issues/841

**Comment by christiancompton** [comment]
Closing as complete.  The SDK is updated - Xcode 10 and Swift 4.2 are fully supported as of version 0.38.0.  I am updating the uplication to use version 1.2.0 in #38.
