### ISSUE TITLE
Doesn't Run on a Physical Device, only runs in Simulator

### ISSUE THREAD

**Issue by sollywelch** [watson-developer-cloud/visual-recognition-coreml#47]
Upon attempting to run the "CoreML Custom" on a physical device it just produces a Thread 1: Signal SIGBART error. However, running on a simulator it works fine?? P

**Comment by bourdakos1** [comment]
My guess is either a camera permission error, or the camera view IBOutlet is broken. Mainly, something wrong with the camera, because the camera isn’t used in the simulator

**Comment by sollywelch** [comment]
Thanks for your reply, that's what I was thinking; it was something to do with the camera permissions. However, after a few hours, I removed all the IBOutlet links between the delegate and the storyboard and tested each one and it turns out that it's the "Simulator Text..." that was causing the error. I didn't need it at all so removed it and all the links. Sorted all my problems!
