### ISSUE TITLE
Update ReadMe with instructions on getting the SDK via CocoaPods

### ISSUE THREAD

**Issue by igor9silva** [watson-developer-cloud/visual-recognition-coreml#7]
Are there any plans on supporting CocoaPods?

**Comment by tbltechnerds** [comment]
I am building this code and will revert.
Referencing https://developer.apple.com/machine-learning/

**Comment by tbltechnerds** [comment]
I can make this work with cocoa pods.

**Comment by igor9silva** [comment]
The documentation for **Watson Swift SDK** only mention Carthage.

**Comment by mediumTaj** [comment]
This is an issue for the [Watson Swift SDK](https://github.com/watson-developer-cloud/swift-sdk). @igor9silva can you create an issue in that repo?

@tbltechnerds if you can help with CocoaPods support it would be great if you can submit a Pull Request!

**Comment by mediumTaj** [comment]
Blocked by CocoaPods support in the Watson Swift SDK.

**Comment by devinaconley** [comment]
Closing this. Support was added in `v0.33.0`.

https://github.com/watson-developer-cloud/swift-sdk/releases/tag/v0.33.0
