### ISSUE TITLE
Is there Watson API for uploading training data and giving link back for created model?

### ISSUE THREAD

**Issue by steve21124** [watson-developer-cloud/visual-recognition-coreml#9]

**Comment by mediumTaj** [comment]
You can use any of [the Watson SDKs](https://github.com/watson-developer-cloud) to upload and train the data in Visual Recognition. 

In Watson Studio, once you have a trained classifier, you can click **Test** on your custom model. From there you can click on the **Implementation** tab > **Core ML**. You should see the download link on the top.

**Comment by SirSpidey** [comment]
@steve21124 Details with examples are in the [API reference](https://www.ibm.com/watson/developercloud/visual-recognition/api/v3/curl.html?curl#retrieve-classifier-details). We haven't documented Swift there yet, but you can see the curl examples.
